### PR TITLE
Update supported Python versions

### PR DESCRIPTION
**Pull request by jmsmkn**
Removes support for Python 3.7 and adds support for Python 3.11.

### CODE REVIEW

**Comment by jmsmkn** [comment]
It seems that https://github.com/pydicom/pylibjpeg-openjpeg does not support Python 3.11 yet.

**Comment by jmsmkn** [comment]
> It seems that https://github.com/pydicom/pylibjpeg-openjpeg does not support Python 3.11 yet.

PR here: https://github.com/pydicom/pylibjpeg-openjpeg/pull/58

**Comment by jmsmkn** [comment]
Same goes for https://github.com/pydicom/pylibjpeg-libjpeg

**Comment by jmsmkn** [comment]
> Same goes for https://github.com/pydicom/pylibjpeg-libjpeg

Two candidates for support there, completely missed the existing PR 🤦‍♂️ Time for the weekend.

https://github.com/pydicom/pylibjpeg-libjpeg/pull/45
https://github.com/pydicom/pylibjpeg-libjpeg/pull/44

**Comment by jmsmkn** [comment]
Support for Python 3.11 has been released in https://pypi.org/project/pylibjpeg-openjpeg/1.3.2/

**Comment by jmsmkn** [comment]
The dependencies now install but we get some seemingly genuine test errors for tiff files on Python 3.11.

**Comment by jmsmkn** [comment]
@miriam-groeneveld could you see a reason for tiff reading being broken with Python 3.11?

**Comment by miriam-groeneveld** [comment]
Not really, I'll have a look

**Comment by miriam-groeneveld** [comment]
It's a change in python 3.11 how enums are stringified, see [here](https://docs.python.org/3/whatsnew/3.11.html#enum) 

>  str(AnIntEnum.ONE) and format(AnIntEnum.ONE) return '1', whereas before str(AnIntEnum.ONE) returned 'AnIntEnum.ONE'

I'll fix it.

**Review by miriam-groeneveld — APPROVED** [review]

**Comment by miriam-groeneveld** [comment]
Thanks for fixing, I created a branch with the tiff fix, but the builds failed and I got distracted with Windows issues

**Comment by jmsmkn** [comment]
> Thanks for fixing, I created a branch with the tiff fix, but the builds failed and I got distracted with Windows issues

Yes I saw, needed to crack on, thanks for the pointer about what was wrong!

**Pull request merged**
